/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projeto.view;

import br.com.projeto.dao.ClienteDAO;
import br.com.projeto.dao.FornecedorDAO;
import br.com.projeto.model.Cliente;
import br.com.projeto.model.Fornecedor;
import br.com.projeto.model.Utilitarios;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gustavo
 */
public class FrmFornecedores extends javax.swing.JFrame {

    public void listar() {

        FornecedorDAO dao = new FornecedorDAO();
        List<Fornecedor> lista = dao.listarFornecedor();
        DefaultTableModel dados = (DefaultTableModel) jTblConsultaFornecedor.getModel();
        dados.setNumRows(0);

        for (Fornecedor c : lista) {

            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getCnpj(),
                c.getEmail(),
                c.getTelefone(),
                c.getCelular(),
                c.getCep(),
                c.getEndereco(),
                c.getNumero(),
                c.getComplemento(),
                c.getBairro(),
                c.getCidade(),
                c.getUf()
            });

        }
    }

    /**
     * Creates new form FrmClientes
     */
    public FrmFornecedores() {
        initComponents();
        jFtfCep.setFocusTraversalKeysEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTpFornecedores = new javax.swing.JTabbedPane();
        jPnCadastro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jFtfCelular = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jFtfTelefone = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jFtfCep = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jTfEndereco = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTfNumero = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTfBairro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTfCidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTfComplemento = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jcbUf = new javax.swing.JComboBox<>();
        jFtfCnpj = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jBtnBuscarPorCnpj = new javax.swing.JButton();
        jPnConsulta = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jtfConsultaNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblConsultaFornecedor = new javax.swing.JTable();
        jBtnNovo = new javax.swing.JButton();
        jBtnSalvar = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Fornecedores");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPnCadastro.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Código:");

        jtfCodigo.setEditable(false);
        jtfCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nome:");

        jtfNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("E-mail:");

        jtfEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Celular:");

        try {
            jFtfCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFtfCelular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Telefone (fixo):");

        try {
            jFtfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFtfTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("CEP:");

        try {
            jFtfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFtfCep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jFtfCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFtfCepActionPerformed(evt);
            }
        });
        jFtfCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFtfCepKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFtfCepKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Endereço:");

        jTfEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Número:");

        jTfNumero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Bairro:");

        jTfBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Cidade:");

        jTfCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Complemento:");

        jTfComplemento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("UF:");

        jcbUf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        try {
            jFtfCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFtfCnpj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("CNPJ");

        jBtnBuscarPorCnpj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search-24.png"))); // NOI18N
        jBtnBuscarPorCnpj.setText("Buscar por CNPJ");
        jBtnBuscarPorCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarPorCnpjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnCadastroLayout = new javax.swing.GroupLayout(jPnCadastro);
        jPnCadastro.setLayout(jPnCadastroLayout);
        jPnCadastroLayout.setHorizontalGroup(
            jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnCadastroLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(10, 10, 10)
                        .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)
                        .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(10, 10, 10)
                        .addComponent(jFtfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnBuscarPorCnpj))
                    .addGroup(jPnCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(10, 10, 10)
                        .addComponent(jFtfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(10, 10, 10)
                        .addComponent(jFtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(10, 10, 10)
                        .addComponent(jFtfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(10, 10, 10)
                        .addComponent(jTfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(10, 10, 10)
                        .addComponent(jTfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(10, 10, 10)
                        .addComponent(jTfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(10, 10, 10)
                        .addComponent(jTfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(10, 10, 10)
                        .addComponent(jTfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(4, 4, 4)
                        .addComponent(jcbUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9))
        );
        jPnCadastroLayout.setVerticalGroup(
            jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnCadastroLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnCadastroLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnCadastroLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3))
                    .addGroup(jPnCadastroLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnCadastroLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel14))
                    .addGroup(jPnCadastroLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFtfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnBuscarPorCnpj))))
                .addGap(18, 18, 18)
                .addGroup(jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFtfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnCadastroLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addGroup(jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFtfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnCadastroLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))))
                .addGap(18, 18, 18)
                .addGroup(jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnCadastroLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)))))
        );

        jTpFornecedores.addTab("Dados Pessoais", jPnCadastro);

        jPnConsulta.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Pesquisar por Nome:");

        jtfConsultaNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfConsultaNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfConsultaNomeKeyPressed(evt);
            }
        });

        jTblConsultaFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CNPJ", "E-mail", "Telefone", "Celular", "CEP", "Endereço", "Nº", "Comp", "Bairro", "Cidade", "UF"
            }
        ));
        jTblConsultaFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblConsultaFornecedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblConsultaFornecedor);
        if (jTblConsultaFornecedor.getColumnModel().getColumnCount() > 0) {
            jTblConsultaFornecedor.getColumnModel().getColumn(0).setResizable(false);
            jTblConsultaFornecedor.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPnConsultaLayout = new javax.swing.GroupLayout(jPnConsulta);
        jPnConsulta.setLayout(jPnConsultaLayout);
        jPnConsultaLayout.setHorizontalGroup(
            jPnConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                    .addGroup(jPnConsultaLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jtfConsultaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPnConsultaLayout.setVerticalGroup(
            jPnConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jtfConsultaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTpFornecedores.addTab("Consulta de Fornecedores", jPnConsulta);

        jBtnNovo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/new-32.png"))); // NOI18N
        jBtnNovo.setText("NOVO");
        jBtnNovo.setEnabled(false);
        jBtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNovoActionPerformed(evt);
            }
        });

        jBtnSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save-32.png"))); // NOI18N
        jBtnSalvar.setText("SALVAR");
        jBtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarActionPerformed(evt);
            }
        });

        jBtnEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/edit-32.png"))); // NOI18N
        jBtnEditar.setText("EDITAR");
        jBtnEditar.setEnabled(false);
        jBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarActionPerformed(evt);
            }
        });

        jBtnExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete-32.png"))); // NOI18N
        jBtnExcluir.setText("EXCLUIR");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTpFornecedores)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jBtnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnSalvar)
                .addGap(18, 18, 18)
                .addComponent(jBtnEditar)
                .addGap(18, 18, 18)
                .addComponent(jBtnExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtnEditar, jBtnExcluir, jBtnNovo, jBtnSalvar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTpFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnSalvar)
                        .addComponent(jBtnEditar)
                        .addComponent(jBtnExcluir)))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtnEditar, jBtnExcluir, jBtnNovo, jBtnSalvar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 863, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jBtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarActionPerformed
        try {

            Fornecedor obj = new Fornecedor();

            // NOME
            if (!"".equals(jtfNome.getText())) {
                obj.setNome(jtfNome.getText());
            }

            // CNPJ
            if (!"".equals(jFtfCnpj.getText())) {
                obj.setCnpj(jFtfCnpj.getText());
            }

            // E-MAIL
            if (!"".equals(jtfEmail.getText())) {
                obj.setEmail(jtfEmail.getText());
            }

            // TELEFONE
            if (!"".equals(jFtfTelefone.getText())) {
                obj.setTelefone(jFtfTelefone.getText());
            }

            // CELULAR
            if (!"".equals(jFtfCelular.getText())) {
                obj.setCelular(jFtfCelular.getText());
            }

            // CEP
            if (!"".equals(jFtfCep.getText())) {
                obj.setCep(jFtfCep.getText());
            }

            // ENDEREÇO
            if (!"".equals(jTfEndereco.getText())) {
                obj.setEndereco(jTfEndereco.getText());
            }

            // NÚMERO
            if (!"".equals(jTfNumero.getText())) {
                obj.setNumero(Integer.parseInt(jTfNumero.getText()));
            }

            // COMPLEMENTO
            if (!"".equals(jTfComplemento.getText())) {
                obj.setComplemento(jTfComplemento.getText());
            }

            // BAIRRO
            if (!"".equals(jTfBairro.getText())) {
                obj.setBairro(jTfBairro.getText());
            }

            // CIDADE
            if (!"".equals(jTfCidade.getText())) {
                obj.setCidade(jTfCidade.getText());
            }

            // UF
            obj.setUf(jcbUf.getSelectedItem().toString());

            FornecedorDAO dao = new FornecedorDAO();
            dao.cadastrarFornecedor(obj);

            new Utilitarios().limpaTela(jPnCadastro);

            jBtnSalvar.setEnabled(false);
            jBtnEditar.setEnabled(false);
            jBtnExcluir.setEnabled(false);
            jBtnNovo.setEnabled(true);

            jtfNome.setEnabled(false);
            jFtfCnpj.setEnabled(false);
            jtfEmail.setEnabled(false);
            jFtfCelular.setEnabled(false);
            jFtfTelefone.setEnabled(false);
            jFtfCep.setEnabled(false);
            jTfEndereco.setEnabled(false);
            jTfNumero.setEnabled(false);
            jTfBairro.setEnabled(false);
            jTfCidade.setEnabled(false);
            jTfComplemento.setEnabled(false);
            jcbUf.setEnabled(false);

        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Falha ao receber dados para cadastro: " + erro.getMessage());
        }
    }//GEN-LAST:event_jBtnSalvarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listar();
    }//GEN-LAST:event_formWindowActivated

    private void jTblConsultaFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblConsultaFornecedorMouseClicked

        // Pega os dados
        try {
            jTpFornecedores.setSelectedIndex(0);

            // CÓDIGO
            Object codigo = jTblConsultaFornecedor.getValueAt(jTblConsultaFornecedor.getSelectedRow(), 0);
            if (codigo != null) {
                jtfCodigo.setText(codigo.toString());
            } else {
                jtfCodigo.setText("");
            }

            // NOME
            Object nome = jTblConsultaFornecedor.getValueAt(jTblConsultaFornecedor.getSelectedRow(), 1);
            if (nome != null) {
                jtfNome.setText(nome.toString());
            } else {
                jtfNome.setText("");
            }

            // CNPJ
            Object cnpj = jTblConsultaFornecedor.getValueAt(jTblConsultaFornecedor.getSelectedRow(), 2);
            if (cnpj != null) {
                jFtfCnpj.setText(cnpj.toString());
            } else {
                jFtfCnpj.setText("");
            }

            // E-MAIL
            Object email = jTblConsultaFornecedor.getValueAt(jTblConsultaFornecedor.getSelectedRow(), 3);
            if (email != null) {
                jtfEmail.setText(email.toString());
            } else {
                jtfEmail.setText("");
            }

            // TELEFONE
            Object telefone = jTblConsultaFornecedor.getValueAt(jTblConsultaFornecedor.getSelectedRow(), 4);
            if (telefone != null) {
                jFtfTelefone.setText(telefone.toString());
            } else {
                jFtfTelefone.setText("");
            }

            // CELULAR
            Object celular = jTblConsultaFornecedor.getValueAt(jTblConsultaFornecedor.getSelectedRow(), 5);
            if (celular != null) {
                jFtfCelular.setText(celular.toString());
            } else {
                jFtfCelular.setText("");
            }

            // CEP
            Object cep = jTblConsultaFornecedor.getValueAt(jTblConsultaFornecedor.getSelectedRow(), 6);
            if (cep != null) {
                jFtfCep.setText(cep.toString());
            } else {
                jFtfCep.setText("");
            }

            // ENDEREÇO
            Object endereco = jTblConsultaFornecedor.getValueAt(jTblConsultaFornecedor.getSelectedRow(), 7);
            if (endereco != null) {
                jTfEndereco.setText(endereco.toString());
            } else {
                jTfEndereco.setText("");
            }

            // NÚMERO
            Object numero = jTblConsultaFornecedor.getValueAt(jTblConsultaFornecedor.getSelectedRow(), 8);
            if (numero != null) {
                jTfNumero.setText(numero.toString());
            } else {
                jTfNumero.setText("0");
            }

            // COMPLEMENTO
            Object complemento = jTblConsultaFornecedor.getValueAt(jTblConsultaFornecedor.getSelectedRow(), 9);
            if (complemento != null) {
                jTfComplemento.setText(complemento.toString());
            } else {
                jTfComplemento.setText("");
            }

            // BAIRRO
            Object bairro = jTblConsultaFornecedor.getValueAt(jTblConsultaFornecedor.getSelectedRow(), 10);
            if (bairro != null) {
                jTfBairro.setText(bairro.toString());
            } else {
                jTfBairro.setText("");
            }

            // CIDADE
            Object cidade = jTblConsultaFornecedor.getValueAt(jTblConsultaFornecedor.getSelectedRow(), 11);
            if (cidade != null) {
                jTfCidade.setText(cidade.toString());
            } else {
                jTfCidade.setText("");
            }

            // UF
            Object uf = jTblConsultaFornecedor.getValueAt(jTblConsultaFornecedor.getSelectedRow(), 12);
            if (uf != null) {
                jcbUf.setSelectedItem(uf.toString());
            } else {
                jcbUf.setSelectedItem("AC");
            }

            jtfNome.setEnabled(true);
            jFtfCnpj.setEnabled(true);

            jtfEmail.setEnabled(true);
            jFtfCelular.setEnabled(true);
            jFtfTelefone.setEnabled(true);
            jFtfCep.setEnabled(true);
            jTfEndereco.setEnabled(true);
            jTfNumero.setEnabled(true);
            jTfBairro.setEnabled(true);
            jTfCidade.setEnabled(true);
            jTfComplemento.setEnabled(true);
            jcbUf.setEnabled(true);
            jBtnBuscarPorCnpj.setEnabled(true);

            jBtnNovo.setEnabled(true);
            jBtnEditar.setEnabled(true);
            jBtnExcluir.setEnabled(true);
            jBtnSalvar.setEnabled(false);

        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Nenhuma linha foi selecionada!");
        }

    }//GEN-LAST:event_jTblConsultaFornecedorMouseClicked

    private void jBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarActionPerformed
        try {

            Fornecedor obj = new Fornecedor();
            obj.setNome(jtfNome.getText());
            obj.setCnpj(jFtfCnpj.getText());
            obj.setEmail(jtfEmail.getText());
            obj.setTelefone(jFtfTelefone.getText());
            obj.setCelular(jFtfCelular.getText());
            obj.setCep(jFtfCep.getText());
            obj.setEndereco(jTfEndereco.getText());
            obj.setNumero(Integer.parseInt(jTfNumero.getText()));
            obj.setComplemento(jTfComplemento.getText());
            obj.setBairro(jTfBairro.getText());
            obj.setCidade(jTfCidade.getText());
            obj.setUf(jcbUf.getSelectedItem().toString());
            obj.setId(Integer.valueOf(jtfCodigo.getText()));

            FornecedorDAO dao = new FornecedorDAO();
            dao.alterarFornecedor(obj);

            new Utilitarios().limpaTela(jPnCadastro);

            jtfNome.setEnabled(false);
            jFtfCnpj.setEnabled(false);

            jtfEmail.setEnabled(false);
            jFtfCelular.setEnabled(false);
            jFtfTelefone.setEnabled(false);
            jFtfCep.setEnabled(false);
            jTfEndereco.setEnabled(false);
            jTfNumero.setEnabled(false);
            jTfBairro.setEnabled(false);
            jTfCidade.setEnabled(false);
            jTfComplemento.setEnabled(false);
            jcbUf.setEnabled(false);
            jBtnBuscarPorCnpj.setEnabled(false);

            jBtnSalvar.setEnabled(false);
            jBtnEditar.setEnabled(false);
            jBtnExcluir.setEnabled(false);
            jBtnNovo.setEnabled(true);

        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Falha ao receber dados para alteração: " + erro.getMessage());
        }
    }//GEN-LAST:event_jBtnEditarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        try {

            int id = Integer.valueOf(jtfCodigo.getText());

            FornecedorDAO dao = new FornecedorDAO();

            if (dao.verificarSeFornecedorTemProduto(id)) {
                JOptionPane.showMessageDialog(null, "Erro: há um produto em estoque cadastrado com este fornecedor!");
            } else {
                dao.excluirFornecedor(id);

                new Utilitarios().limpaTela(jPnCadastro);

                jtfNome.setEnabled(false);
                jFtfCnpj.setEnabled(false);

                jtfEmail.setEnabled(false);
                jFtfCelular.setEnabled(false);
                jFtfTelefone.setEnabled(false);
                jFtfCep.setEnabled(false);
                jTfEndereco.setEnabled(false);
                jTfNumero.setEnabled(false);
                jTfBairro.setEnabled(false);
                jTfCidade.setEnabled(false);
                jTfComplemento.setEnabled(false);
                jcbUf.setEnabled(false);
                jBtnBuscarPorCnpj.setEnabled(false);

                jBtnSalvar.setEnabled(false);
                jBtnEditar.setEnabled(false);
                jBtnExcluir.setEnabled(false);
                jBtnNovo.setEnabled(true);
            }

        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Falha ao receber dados para exclusão: " + erro.getMessage());
        }
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jtfConsultaNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfConsultaNomeKeyPressed
        // Botão pesquisar

        String nome = jtfConsultaNome.getText();

        FornecedorDAO dao = new FornecedorDAO();
        List<Fornecedor> lista = dao.pesquisaFornecedoresPorNome(nome);
        DefaultTableModel dados = (DefaultTableModel) jTblConsultaFornecedor.getModel();
        dados.setNumRows(0);

        for (Fornecedor c : lista) {

            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getCnpj(),
                c.getEmail(),
                c.getCelular(),
                c.getTelefone(),
                c.getCep(),
                c.getEndereco(),
                c.getNumero(),
                c.getBairro(),
                c.getCidade(),
                c.getComplemento(),
                c.getUf()
            });

        }
    }//GEN-LAST:event_jtfConsultaNomeKeyPressed

    private void jBtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNovoActionPerformed
        new Utilitarios().limpaTela(jPnCadastro);

        jtfNome.requestFocus();
        jBtnNovo.setEnabled(false);
        jBtnSalvar.setEnabled(true);
        jBtnEditar.setEnabled(false);
        jBtnExcluir.setEnabled(false);

        jtfNome.setEnabled(true);
        jFtfCnpj.setEnabled(true);

        jtfEmail.setEnabled(true);
        jFtfCelular.setEnabled(true);
        jFtfTelefone.setEnabled(true);
        jFtfCep.setEnabled(true);
        jTfEndereco.setEnabled(true);
        jTfNumero.setEnabled(true);
        jTfBairro.setEnabled(true);
        jTfCidade.setEnabled(true);
        jTfComplemento.setEnabled(true);
        jcbUf.setEnabled(true);
        jBtnBuscarPorCnpj.setEnabled(true);
    }//GEN-LAST:event_jBtnNovoActionPerformed

    private void jFtfCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFtfCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFtfCepActionPerformed

    private void jBtnBuscarPorCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarPorCnpjActionPerformed
        // Botão buscar por CNPJ

        String cnpj = jFtfCnpj.getText();

        Fornecedor obj = new Fornecedor();

        FornecedorDAO dao = new FornecedorDAO();

        obj = dao.consultaPorCnpj(cnpj);

        if (obj != null) {
            // Exibir os dados nos campos de texto
            jtfCodigo.setText(String.valueOf(obj.getId()));
            jtfNome.setText(obj.getNome());
            jtfEmail.setText(obj.getEmail());
            jFtfTelefone.setText(obj.getTelefone());
            jFtfCelular.setText(obj.getCelular());
            jFtfCep.setText(obj.getCep());
            jTfEndereco.setText(obj.getEndereco());
            jTfNumero.setText(String.valueOf(obj.getNumero()));
            jTfComplemento.setText(obj.getComplemento());
            jTfBairro.setText(obj.getBairro());
            jTfCidade.setText(obj.getCidade());
            jcbUf.setSelectedItem(obj.getUf());

            jtfNome.setEnabled(true);
            jtfEmail.setEnabled(true);
            jFtfCelular.setEnabled(true);
            jFtfTelefone.setEnabled(true);
            jFtfCep.setEnabled(true);
            jTfEndereco.setEnabled(true);
            jTfNumero.setEnabled(true);
            jTfBairro.setEnabled(true);
            jTfCidade.setEnabled(true);
            jTfComplemento.setEnabled(true);
            jcbUf.setEnabled(true);
            jBtnBuscarPorCnpj.setEnabled(true);

            jBtnEditar.setEnabled(true);
            jBtnExcluir.setEnabled(true);
            jBtnSalvar.setEnabled(false);
            jBtnNovo.setEnabled(true);
        }

        jtfNome.requestFocus();
    }//GEN-LAST:event_jBtnBuscarPorCnpjActionPerformed

    private void jFtfCepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFtfCepKeyPressed
        // Busca por CEP quando teclar Enter

        //Programacao do keypress
        try {
            if (evt.getKeyCode() == KeyEvent.VK_TAB || evt.getKeyCode() == KeyEvent.VK_ENTER) {
                Cliente obj = new Cliente();
                ClienteDAO dao = new ClienteDAO();
                obj = dao.buscaCep(jFtfCep.getText());

                jTfEndereco.setText(obj.getEndereco());
                jTfBairro.setText(obj.getBairro());
                jTfCidade.setText(obj.getCidade());
                jcbUf.setSelectedItem(obj.getUf());

                jTfNumero.requestFocus();

            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Endereço não encontrado!");
        }

    }//GEN-LAST:event_jFtfCepKeyPressed

    private void jFtfCepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFtfCepKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jFtfCepKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFornecedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscarPorCnpj;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnNovo;
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JFormattedTextField jFtfCelular;
    private javax.swing.JFormattedTextField jFtfCep;
    private javax.swing.JFormattedTextField jFtfCnpj;
    private javax.swing.JFormattedTextField jFtfTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPnCadastro;
    private javax.swing.JPanel jPnConsulta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblConsultaFornecedor;
    private javax.swing.JTextField jTfBairro;
    private javax.swing.JTextField jTfCidade;
    private javax.swing.JTextField jTfComplemento;
    private javax.swing.JTextField jTfEndereco;
    private javax.swing.JTextField jTfNumero;
    private javax.swing.JTabbedPane jTpFornecedores;
    private javax.swing.JComboBox<String> jcbUf;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfConsultaNome;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfNome;
    // End of variables declaration//GEN-END:variables
}
